### ISSUE TITLE
change mParentItemList

### ISSUE THREAD

**Issue by JakeWang123** [bignerdranch/expandable-recycler-view#185] opened 2016-03-25 08:31 UTC
How can I change the mParentItemList data or set mParentItemList?

**Comment by paul-turner** [comment] 2016-03-29 14:48
@JakeWang123 If you keep a reference to the arraylist you pass during construction of the adapter object you can make changes to it and they will be reflected in the adapters object. Just make sure you call the corresponding notifyParent/notifyChild methods.

**Comment by FilenkovMaxim** [comment] 2016-06-01 10:22
But which method can update whole dataset, not by one item?
I tried adapter.notifyDataSetChanged(); but without result.

**Comment by jotish** [comment] 2016-06-04 06:19
What if my whole list (parent+ child) has changed and I want to call notifyDataSetchanged. Not individual notifyParent/ notifyChild ?

@paul-turner @JakeWang123

**Comment by paul-turner** [comment] 2016-06-22 17:34
@FilenkovMaxim @jotish Unfortunately there is not yet a method for that, would need to swap out the adapters as a whole. The feature to add such a method is being tracked here: https://github.com/bignerdranch/expandable-recycler-view/issues/89

**Comment by FilenkovMaxim** [comment] 2016-07-19 11:20
@paul-turner and it seems to me notifyParent/ notifyChild methods don't work properly. Am I wrong?
I have hierarchical checkboxes and I need to check / uncheck child checkboxes when parent changes. I've changed dataset, but views didn't refresh their images and notifyParent didn't nothing.

**Comment by paul-turner** [comment] 2016-07-21 17:35
@FilenkovMaxim You might be right (as far as we've tested those methods work as intended), hard to tell without details on code. I'd recommend opening an issue with steps to reproduce!

**Comment by paul-turner** [comment] 2016-10-07 21:31
Hello, we've released 3.0.0-RC1 with a fix for this issue (we've added a setter for the whole list, though it is not recommended that you use it). 

I would love your feedback with any issues you have with the solution before we make 3.0.0 final. Check out the Pull Request that contains the fix for your issue (should be referenced above), and the [changelog](https://github.com/bignerdranch/expandable-recycler-view/releases/tag/v3.0.0-RC1) for a list of changes that have come with 3.0.0 (there are a lot of them!). 

If you have any issues feel free to re-open this issue with details of what you are seeing.

**Closed by paul-turner** 2016-10-07 21:31 UTC
Labels: question
