### ISSUE TITLE
When expand one item, how to collapse all the others

### ISSUE THREAD

**Issue by nicopasso** [bignerdranch/expandable-recycler-view#90] opened 2015-09-30 13:14 UTC
Hi,
I'm trying to find a way to collapse all the expanded parent item when another one is expanding.
Is it possible?

**Comment by pythoneer** [comment] 2015-09-30 13:34
This is in principle doable (i've done that in version 1.0.3 with this library see https://github.com/bignerdranch/expandable-recycler-view/issues/55 as reference to close parents prior to version 2.0.0 ) but i think in this version there is a bug see https://github.com/bignerdranch/expandable-recycler-view/issues/91 as an (not yet working) excample

**Comment by nicopasso** [comment] 2015-09-30 15:22
I try your VERSION3 solution and it works. But unfortunately I've a particular layout who animates based on collapsing/expanding. 

@pythoneer I have another small question...how can I determine the parent position based on one of the children click event (assuming to have more than one parent opened)?

**Comment by pythoneer** [comment] 2015-09-30 16:00
@nicopasso regarding your position problem. The easiest way would be to use the version suggested by paul-turner at my other issue #91 . Do not use the ontouch listener cuz it was just a workaround. if you use the version from paul-turner you already get the clicked item position if you need to scroll the view to that position – like myself – use this code instead


```java
        @Override
        public void onParentListItemExpanded(int position) {
            Object parent = mItemList.get(position);
            collapseAllParents();
            position = mItemList.indexOf(parent);
            LinearLayoutManager llm = (LinearLayoutManager) mRecyclerView.getLayoutManager();
            llm.scrollToPositionWithOffset(position, 0);
            // Alternatively keep track of the single item that is expanded and explicitly collapse that row (more efficient)
            super.onParentListItemExpanded(position);
        }
```

**Comment by nicopasso** [comment] 2015-10-01 09:58
With this solution seems like when a click occurs on an expanded parent item, the expanded parent is not collapsing anymore. It collapse only when the click occurs on one of the others collapsed parent.  

I'm doing something wrong?

**Comment by pythoneer** [comment] 2015-10-01 10:18
@nicopasso i have the same behavior. I guess its due to the effect of callapsing all items while one – the current one – is also expanding. I've not looked at the library code but i guess the lib code is toggling instead of following the "real" state and setting it expanded or collapsed. Some kind of race condition i would say. So to avoid this, you simply collapse all parents but the current one being clicked on. This works for me:

```java
        @Override
        public void onParentListItemExpanded(int position) {
            Object parent = mItemList.get(position);
//            collapseAllParents();
            for(int idx = 0; idx < mItemList.size(); idx++) {
                if(idx != position) {
                    collapseParent(idx);
                }
            }
            position = mItemList.indexOf(parent);
            LinearLayoutManager llm = (LinearLayoutManager) mRecyclerView.getLayoutManager();
            llm.scrollToPositionWithOffset(position, 0);
            // Alternatively keep track of the single item that is expanded and explicitly collapse that row (more efficient)
            super.onParentListItemExpanded(position);
        }
```

**Comment by nicopasso** [comment] 2015-10-01 10:52
That didn't work for me.

I've an ArrayIndexOutOfBound exception...I think my problem is that I have more than one children under a parent and this could lead to a "bad" indexing of the parents.
Right now I've 4 parents and 8 children for every parent. 
The logcat tells me that the lenght of the mItemList is 12 instead of 4, beacuse I've opened the first parent and the array add the 8 children to the mItemList.

**Comment by kyogs** [comment] 2015-10-01 12:41
I have used your code and got ArrayIndexOutOfBound exception.I have check when scroll with expand view then list size increase by 1 automatically.I have modify in your code and its working fine.but this is not good solution.

        @Override
        public void onParentListItemExpanded(int position) {
            Object parent = mItemList.get(position);
//            collapseAllParents();
            for(int idx = 0; idx < mItemList.size(); idx++) {
                if (idx != position && idx < mItemList.size() - 1) {
                    collapseParent(idx);
                }
            }
            position = mItemList.indexOf(parent);
            LinearLayoutManager llm = (LinearLayoutManager) mRecyclerView.getLayoutManager();
            llm.scrollToPositionWithOffset(position, 0);
            // Alternatively keep track of the single item that is expanded and explicitly collapse that row (more efficient)
            super.onParentListItemExpanded(position);
        }

**Comment by paul-turner** [comment] 2015-10-01 14:05
Below is a quick solution. The issue lies in the call to collapse all, this changes the view of item we are about to expand to think it is collapsed even though it isn't. I'd recommend keeping track of the last expanded item instead.

We are thinking of making this a "mode" of expansion for the library, so all you have to do is set the mode when creating the adapter and we will take care of only having one expanded at the time. For now the below should fill your needs.
``` java
    @Override
    public void onParentListItemExpanded(int position) {
        Object parent = mItemList.get(position);
        collapseAllParents();    // Alternatively keep track of the single item that is expanded and explicitly collapse that row (more efficient)
        expandParent(((ParentWrapper) parent).getParentListItem());
    }
```

**Comment by paul-turner** [comment] 2015-10-08 18:54
Closing this for now, will create a new issue for tracking the ideas of expand modes for the library

**Closed by paul-turner** 2015-10-08 18:54 UTC
Labels: question

**Comment by vsay01** [comment] 2015-11-16 18:13
Hi @paul-turner 

I used the code you provided in my MyExpandableAdapter.java

Everything works fine but after i browse the application, change the device configuration to landscape and switch to another application there was an error occurred related to 
ArrayIndexOutOfBound in the `mExpandableAdapter.onRestoreInstanceState(savedInstanceState);`

`Caused by: java.lang.IndexOutOfBoundsException: Invalid index 20, size is 20`
`at com.bignerdranch.expandablerecyclerview.Adapter.ExpandableRecyclerAdapter.getListItem(ExpandableRecyclerAdapter.java:490)`
`at com.bignerdranch.expandablerecyclerview.Adapter.ExpandableRecyclerAdapter.onRestoreInstanceState(ExpandableRecyclerAdapter.java:445)`
`at com.eyey.android.eyeynews.ui.MainActivity.onRestoreInstanceState(MainActivity.java:87)`

How can i solved this issue?
Thank

**Comment by paul-turner** [comment] 2015-11-16 19:51
@vsay01 does the crash still occur if you don't have the code I provided? it seems like this issue may be separate from the changes I suggest.

**Comment by vsay01** [comment] 2015-11-17 00:43
@paul-turner I tried tested it again.
I just tested it again, thing a bit different, When I put your code things work fine even i change device configuration and browse around however after a while of running by changing back and forth the applications. The same error occurred.

When i don't use your code, things work fine.
What should I do?

**Comment by paul-turner** [comment] 2015-11-17 16:02
@vsay01 I've made a new issue (#122) to track this crash, the problem is with the restoring of state somehow, might be more likely to happen with the code we talk about here (and that is noted in the issue)

**Comment by samy-baili** [comment] 2015-12-18 09:42
Hi guys,
I have the same issue, that occurs when there is already a child expanded.

**Comment by dgreenhalgh** [comment] 2015-12-29 15:02
@samy-baili, are you saying that you're seeing the same crash as the one in #122?

**Comment by NsAveek** [comment] 2017-02-13 08:50
onBindParentViewHolder > parentPosition is always coming 0.

**Comment by paul-turner** [comment] 2017-02-14 20:05
@NsAveek Can you be more specific with what issue you are seeing. Please open a new issue if you are seeing a bug. This issue is just a question with suggested answers.

**Comment by htooaunghlaing** [comment] 2017-02-24 10:39
Declare
`private int lastExpandedPosition = -1;`
I used a trick from Expandable ListView,

```
mAdapter.setExpandCollapseListener(new ExpandableRecyclerAdapter.ExpandCollapseListener() {
            @UiThread
            @Override
            public void onParentExpanded(int parentPosition) {
                if (lastExpandedPosition != -1
                        && parentPosition != lastExpandedPosition) {
                    mAdapter.collapseParent(lastExpandedPosition);
                }
                lastExpandedPosition = parentPosition;
            }

            @UiThread
            @Override
            public void onParentCollapsed(int parentPosition) {

            }
        });
```

**Comment by pedrohdsl** [comment] 2017-03-17 13:57
Following @htooaunghlaing, i just adjust scroll position like @pythoneer answer and its work fine.


      
      mAdapter.setExpandCollapseListener(new ExpandableRecyclerAdapter.ExpandCollapseListener() {
                @UiThread
                @Override
                public void onParentExpanded(int parentPosition) {
                    if (lastExpandedPosition != -1
                            && parentPosition != lastExpandedPosition) {
                        mAdapter.collapseParent(lastExpandedPosition);
                    }
                    lastExpandedPosition = parentPosition;
                    LinearLayoutManager llm = (LinearLayoutManager) mRecyclerView.getLayoutManager();
                    llm.scrollToPositionWithOffset(parentPosition, 0);
                }

                @UiThread
                @Override
                public void onParentCollapsed(int parentPosition) {

                }
            });

**Comment by pollux-** [comment] 2017-07-13 15:11
@pedrohdsl I was scratching my head for this,  Thanks

**Comment by ajibadeseun** [comment] 2017-12-06 10:01
@htooaunghlaing, thanks a lot for your suggestion

**Comment by marlonpya** [comment] 2018-03-22 19:35
have a question the others father items (not visibles because not see in size my phone), have a fix.

- item not see
init screen
- item
- item
- item
end screen
- item not see

my items not see never update
