### ISSUE TITLE
Only the arrow of the last ParentItem is animated 

### ISSUE THREAD

**Issue by moloti** [bignerdranch/expandable-recycler-view#146] opened 2016-01-05 20:01 UTC
I successfully installed the Expandable RecyclerView everythink works fine. Then I wanted to add an animation to the arrow. I installed it as described in the documentation and here is the issue, no matter on which ParentItem I click, always the arrow of the last item is animated. What could be the reason for that issue? I need some help.

**Comment by paul-turner** [comment] 2016-01-05 22:11
Interesting @moloti, might it help to compare your implementation to what we did in https://github.com/bignerdranch/expandable-recycler-view/blob/master/app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/VerticalParentViewHolder.java ?

If not I will need a couple more details  (maybe the ParentViewHolder changes you've made) to see what might be the cause.

**Comment by moloti** [comment] 2016-01-06 11:54
Thank you for the quick response. I already compared it with the VerticalParentViewHolder.
This is MyParentViewHolder, maybe you will find some mistakes:

public class MyParentViewHolder extends ParentViewHolder {
    private static final float INITIAL_POSITION = 0.0f;
    private static final float ROTATED_POSITION = 180f;
    private static final boolean HONEYCOMB_AND_ABOVE = Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB;


    public static TextView categorieTitleParent;
    public static ImageView categorieImageParent;
    public static ImageView categorieImageArrowParent;

    public MyParentViewHolder(View itemView) {
        super(itemView);

        categorieTitleParent = (TextView) itemView.findViewById(R.id.row_categorie_title_parent);
        categorieImageParent = (ImageView) itemView.findViewById(R.id.row_categorie_image_parent);
        categorieImageArrowParent = (ImageView) itemView.findViewById(R.id.row_categorie_arrow_parent);

        categorieImageArrowParent.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (isExpanded()) {
                    collapseView();

                }else{
                    expandView();

                }
            }
        });

    }
    @SuppressLint("NewApi")
    @Override
    public void setExpanded(boolean expanded) {
        super.setExpanded(expanded);
        if (!HONEYCOMB_AND_ABOVE) {
            return;
        }

        if (expanded) {
            categorieImageArrowParent.setRotation(ROTATED_POSITION);
        } else {
            categorieImageArrowParent.setRotation(INITIAL_POSITION);
        }
    }
    
    
    @Override
    public boolean shouldItemViewClickToggleExpansion() {
        return false;
    }
}

**Comment by paul-turner** [comment] 2016-01-06 20:40
Everything looks correct to me. Going to try some troubleshooting questions:

Is the data in the adapter changing position or changing items while the list is displayed? or is the data static through the lifetime?

Are you inflating/creating a new view every time in `onCreateParentViewHolder`?

It might help If I can see your adapter subclass and if the problem is somewhere in there maybe.

**Comment by moloti** [comment] 2016-01-07 19:20
I still don't find the bug and I think my data is static through the lifetime except if the adapter called every time I expand an Item? But here is the methode where I generate my data for the adapter in my fragment class, :


private List<ParentListItem> generateCategories(Context context){
        Integer pos = 0;
        PopulateCategories populateCategories = PopulateCategories.get(getActivity());
        List<CategorieDataParent> parentCategories = populateCategories.getParentCategories();
        List<ParentListItem> parentListItems = new ArrayList<>();

        for (CategorieDataParent categorieDataParent : parentCategories) {

            List<CategorieDataChild> childItemList = populateCategories.getChildCategories(context ,pos);
            categorieDataParent.setChildItemList(childItemList);
            parentListItems.add(categorieDataParent);
            pos++;
        }

        return parentListItems;
    }

And here my whole adapter class, but I don't think that the mistake is here:


public class MyExpandableRecyclerAdapter extends ExpandableRecyclerAdapter<MyParentViewHolder, MyChildViewHolder> {
    private LayoutInflater mInflater;

    public MyExpandableRecyclerAdapter(Context context, List<ParentListItem> itemList){
        super(itemList);
        mInflater = LayoutInflater.from(context);

    }
    @Override
    public MyParentViewHolder onCreateParentViewHolder(ViewGroup parent) {
        View view = mInflater.inflate(R.layout.categorie_row_parent, parent, false);
        return new MyParentViewHolder(view);
    }

    @Override
    public MyChildViewHolder onCreateChildViewHolder(ViewGroup parent) {
        View view = mInflater.inflate(R.layout.categorie_row_child, parent, false);
        return new MyChildViewHolder(view);
    }

    @Override
    public void onBindParentViewHolder(MyParentViewHolder parentViewHolder, int position, ParentListItem parentListItem) {
        CategorieDataParent categorieDataParent = (CategorieDataParent) parentListItem;
        MyParentViewHolder.categorieTitleParent.setText(categorieDataParent.getCategorie());
        MyParentViewHolder.categorieImageParent.setImageDrawable(categorieDataParent.getDrawable());


    }

    @Override
    public void onBindChildViewHolder(MyChildViewHolder childViewHolder, int position, Object childListItem) {
        CategorieDataChild categorieDataChild = (CategorieDataChild) childListItem;
        MyChildViewHolder.categorieTitleChild.setText(categorieDataChild.getCategorie());
        MyChildViewHolder.categorieImageChild.setImageDrawable(categorieDataChild.getDrawable());
    }
}

**Comment by paul-turner** [comment] 2016-01-07 20:04
Found the problem, it was in the first code sample you gave me:
```java
public static TextView categorieTitleParent;
public static ImageView categorieImageParent;
public static ImageView categorieImageArrowParent;
```

Because these are marked as `static` they are being used as a single global variable which means that only the last row to be created gets stored. I think everything should work as intended if you remove the `static` from those variables.

**Comment by moloti** [comment] 2016-01-08 00:04
Thank you for your help that was the problem, now it works prefect! But in my case I can only remove the static from the ImageView responsible for the arrow, else I get an error. The other two views must be static, because I reference them in my adapter.

**Closed** 2016-01-08 00:05 UTC
Labels: question
